/* USER BOUND */
export const USER_BOUND_INITIALIZE = "USER_BOUND_INITIALIZE";
export const USER_BOUND_UPDATE_ON_ZOOM = "USER_BOUND_UPDATE_ON_ZOOM";
export const USER_BOUND_UPDATE_ON_MOVE = "USER_BOUND_UPDATE_ON_MOVE";

/* Buffered Extents */
export const BUFFERED_EXTENTS_INITIALIZE = "BUFFERED_EXTENTS_INITIALIZE";
export const BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_NO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_ONE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_TWO_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST =
  "BUFFERED_EXTENTS_UPDATE_ON_THREE_INTERSECTIONS_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_SUCCESS =
  "BUFFERED_EXTENTS_UPDATE_SUCCESS";

/* Cached Data */
export const CACHED_DATA_UPDATE_REQUEST = "CACHED_DATA_UPDATE_REQUEST";
export const CACHED_DATA_UPDATE_SUCCESS = "CACHED_DATA_UPDATE_SUCCESS";
export const CACHED_DATA_INITIALIZE = "CACHED_DATA_INITIALIZE";
