/* USER BOUND */
export const USER_BOUND_INITIALIZE = "USER_BOUND_INITIALIZE";
export const USER_BOUND_UPDATE_ON_ZOOM = "USER_BOUND_UPDATE_ON_ZOOM";
export const USER_BOUND_UPDATE_ON_MOVE = "USER_BOUND_UPDATE_ON_MOVE";

/* Buffered Extents */
export const BUFFERED_EXTENTS_INITIALIZE = "BUFFERED_EXTENTS_INITIALIZE";
export const BUFFERED_EXTENTS_UPDATE_REQUEST = "BUFFERED_EXTENTS_UPDATE_REQUEST";
export const BUFFERED_EXTENTS_UPDATE_SUCCESS = "BUFFERED_EXTENTS_UPDATE_SUCCESS";
