/* USER BOUND */
export const USER_BOUND_INITIALIZE = "USER_BOUND_INITIALIZE";
export const USER_BOUND_UPDATE_ON_ZOOM = "USER_BOUND_UPDATE_ON_ZOOM";
export const USER_BOUND_UPDATE_ON_MOVE = "USER_BOUND_UPDATE_ON_MOVE";

/* Buffered Extents */
export const BUFFERED_EXTENT_INITIALIZE = "BUFFERED_EXTENT_INITIALIZE";
export const BUFFERED_EXTENT_UPDATE = "BUFFERED_EXTENT_UPDATE";
